### ISSUE TITLE
wall run/clip bug

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#221] opened 2015-06-28 16:53 UTC
Seems there's some issues when transitioning from clip material to geometry where you get stuck kicking off an invisible wall.

http://dl.dropbox.com/u/14141289/RE/parkourbug.mp4

**Comment by shirepirate** [comment] 2015-06-28 19:49
this is caused by placing material in an odd way inside of the geometry, also mentioned here
http://redeclipse.net/forum/viewtopic.php?f=7&t=738

if you use the proper sized cube (or remove all the clip from inside of that wall) it doesn't occur.

**Comment by acerspyro** [comment] 2015-06-28 19:52
Yep, I experienced the same thing in my Center re-vamp. Some really weird shit is going on. https://drive.google.com/file/d/0B8LVgU2QCQy0aW96VjRvQnJZX28/view?usp=sharing

**Comment by JeffBobbo** [comment] 2015-06-28 19:53
This isn't just on bloodlust, it happens on lots of maps, this was just the easiest to reproduce. Also, I believe the engine optimises materials into geometry if it makes no overall change (and this is easily testable), which makes this unfixible by modifying the map.

**Comment by shirepirate** [comment] 2015-06-28 19:56
i just fixed your exact example by modifying the map.

**Comment by JeffBobbo** [comment] 2015-06-28 20:04
@shirepirate I just checked my version of the map, there's no clip material inside the geometry. Could you explain your 'fix'?

**Comment by JeffBobbo** [comment] 2015-06-28 20:22
@shirepirate done some testing, I managed to 'fix it' by adding clip material to that piece of geometry, but when I then recomputed the light map it is was removed bringing the issue back again.

Given that this issue is present on multiple maps and isn't easy or intuitive to fix, can you please reopen this issue so it can be fixed properly?

**Comment by JeffBobbo** [comment] 2015-06-28 22:17
This is also effecting some other maps maps which I just tested:
* battlefield
* biolytic
* bloodlust
* deli
* pumpstation

There are possibly others, I only done a quick check.

**Comment by shirepirate** [comment] 2015-06-28 22:32
will have the engine guy confirm if it is actual fixable issue or not

**Comment by qreeves** [comment] 2015-07-06 09:31
I think this more has to do with how we're doing the angle tests. Will require some major testing on my behalf, so triaging for now.

**Comment by qreeves** [comment] 2015-07-21 13:52
I had an idea which I've done in 3027c02 to see if this improves things.

**Comment by shirepirate** [comment] 2015-07-29 00:12
3027c0244ac6aa604477d1d06f319a4296e90b3e did not improve things

**Comment by qreeves** [comment] 2015-07-29 02:05
Can someone create a map with the sole purpose of demonstrating this bug so I have a test case?

**Comment by zaquest** [comment] 2016-10-21 12:39
This has to do with remipping it seems. [This](http://aceclan.tk/static/good.mpz) is the original variant of the test map, it has no clipping material inside geometry or anything odd, bug doesn't occur. [This](http://aceclan.tk/static/bad.mpz) is what you get after /remip on the previous map. Bug occurs only on one side of the wall. I should add that this bug affects not only wall running, but also climbing, and simple jumping close enough to the wall. When it affects climbing it's especially annoying since it often results in you falling in a pit even though you had more than enough impulse to climb back.

**Comment by qreeves** [comment] 2016-10-22 04:27
I'm wondering if we should just disable clip material in the parkour simulation physics. Is there any known use case where you need clip material to parkour/etc?

**Comment by IceflowRE** [comment] 2016-10-22 11:04
Yes, maybe a small uneven ground, which you want to clip.

**Comment by JeffBobbo** [comment] 2016-10-22 13:51
>I'm wondering if we should just disable clip material in the parkour simulation physics. Is there any known use case where you need clip material to parkour/etc?

Definitely not the thing to do. Clip is used in a lot of places to allow surfaces to be parkoured on easily and allow detail to be added to the geometry, for example, basically all the windows on ubik:
![image](https://cloud.githubusercontent.com/assets/5425481/19619804/e8d1b044-9866-11e6-9ebb-e055fb360dcb.png)

**Comment by zaquest** [comment] 2017-08-29 12:34
After some testing I believe there are at least two issues with collision detection at the moment.

The first appears to be a rounding problem. [Here](https://github.com/red-eclipse/base/blob/master/src/engine/physics.cpp#L1196) the margin is added to avoid it on one side, but not on the other, hence on a test map that I created the bug appears only on one side. If that line is removed the bug appears on the other side of the wall too. If instead a similar line `bo.sub(1);` is added the bug goes away.

The second is more complicated. Since collision detection treats solid geometry and clip material in a different ways ([here](https://github.com/red-eclipse/base/blob/master/src/engine/physics.cpp#L928) in particular), all faces of a clipped cube are checked for collision and if a player happens to be on an edge of a clipped cube, sometimes the engine decides that a face that is inside of the clipped area (e.g. left of right face) is more appropriate (closer to the player) than the face that is desired (front face, the one player is trying to use for parkour). So the engine sets `collidewall` to a value that makes the game think player wants to wall run. This bug affects `ghost`'s windows. As the description implies the bug occurs on any clip material. I tested it on a new map that had nothing but a wall of clip material - if you climb it up for long enough at some places it just won't work, instead it tries to wall run on an inner face.

I also suggest this bug was given a higher priority since it actually breaks the game.

**Comment by qreeves** [comment] 2018-01-18 04:06
Reports are this has improved in the development version, so I'm closing this issue. Let us know if it reappears.

**Closed by qreeves** 2018-01-18 04:06 UTC
Labels: bug

**Comment by JeffBobbo** [comment] 2018-02-03 01:01
Perhaps not related, but I had a very similar issue appear play testing on 2.0 tonight. afaik clip wasn't involved but I tried to wall kick off the edge of an arch on Castle and it done just as would in 1.5/6. Was half on the edge though, so not so bad in this instance.
