### ISSUE TITLE
libpng warnings

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#625] opened 2016-12-07 20:01 UTC
For as long as I could remember, the game always had these gnarly libpng warnings, either about incorrect color profiles or interlace handling.

```
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: known incorrect sRGB profile
```

If the warnings are not triggered by bugs, either:
- The relevant textures should be fixed, or
- The warnings should be muted and only be shown in verbose mode.

![screenshot from 2016-12-07 14-48-43](https://cloud.githubusercontent.com/assets/4400999/20984409/1288b054-bc8e-11e6-8b10-2aefb3a0d22a.png)

**Comment by acz13** [comment] 2016-12-07 20:42
for `libpng warning: Interlace handling should be turned on when using png_read_image` can't we just turn on Interlace handling?

`png_set_interlace_handling` perhaps?

**Comment by qreeves** [comment] 2016-12-08 03:33
This is SDL's internal PNG reading. which is pretty much impossible to control entirely. The rest of the code doesn't even use libpng, it writes the files itself using zlib.

**Comment by TheAssassin** [comment] 2016-12-12 13:23
As long as we don't put any interlaced PNGs in the data repository, there won't be any problems I guess.

Looks like one of the problems the package maintainers have to take care of: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809038

I cannot reproduce the bug on my Xubuntu 16.04.1. Therefore we need information on what systems it occurs and whether we can even fix that problem (or if it has been fixed already in the latest distro versions).
@acerspyro: what OS (incl. version) do you use? What version of SDL2_image and libpng is installed on your system?

**Comment by acerspyro** [comment] 2016-12-22 01:04
@TheAssassin The bug was present on a fresh Ubuntu 16.10 install (I don't have it on hand, but I assume it's the latest version SDL2_image and libpng available at this time)

**Comment by TheAssassin** [comment] 2016-12-22 01:10
@acerspyro I will try to reproduce this on a fresh Debian testing environment (has the same versions as Ubuntu 16.10, but without Canonical patches) and see what's going to happen. If it goes well, I'll test it on Ubuntu 16.10.
(Shouldn't forget to mention that I'm doing this in Docker containers, but that shouldn't change the compiler behaviour.)

**Comment by TheAssassin** [comment] 2016-12-22 01:29
Worked perfectly fine on Debian testing (build log: https://paste.kde.org/pyoe7pw3m/dtvmyk), except for the two warnings that are going to be fixed by PR #643.
Testing on Ubuntu 16.10 Docker image now, going to update the comment with a log ASAP.

**Comment by acerspyro** [comment] 2016-12-22 02:31
**List of pertinent library versions**
https://gist.github.com/anonymous/52a46215e7c09ad35e68332335772bb9

**Make build log**
https://gist.github.com/acerspyro/a52ab6f4062d2e5328e03a9322d52b17

**Comment by TheAssassin** [comment] 2016-12-22 04:09
@acerspyro looks like I'll have to set up a full VM to get a valid test environment.
I lowered the priority though, as this does not seem to be a breaking issue, but just an annoying runtime warning we are not responsible for.

**Comment by TheAssassin** [comment] 2016-12-22 14:48
Update:

I can reproduce the messages in a VirtualBox VM running Xubuntu 16.10.
The first type of warnings is not related to SDL2_image. The problem is that libpng 1.6+ has stricter checks than the older versions. It appears to be safe to ignore the warning. As this is libpng's internal code, we have no chance to modify that behaviour. But we could try to remove the broken iCCP profiles from all the pngs we use. ([source](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile))

The second warning is caused by a wrong call to `libpng_read_image` in SDL2_image, as the libpng devs pointed out [here](https://sourceforge.net/p/libpng/bugs/237/). It appears to be safe to ignore this warning, too, as our PNGs don't use interlacing. Someone might want to file a bug at SDL2_image's issue tracker about that.

I think we should keep the issue open until SDL2_image fix their code.

**Comment by qreeves** [comment] 2017-11-04 11:50
Not something we can fix on our end.

**Closed by qreeves** 2017-11-04 11:50 UTC
Labels: low priority, needs verifying
