### ISSUE TITLE
I can't run redeclipse.sh

### ISSUE THREAD

**Issue by Danfun64** [red-eclipse/base#60] opened 2015-02-18 18:59 UTC
redeclipse.sh worked perfectly yesterday, but when you updated the git base, I get this:

http://paste.debian.net/151677/

**Comment by ienorand** [comment] 2015-02-18 19:21
Closing as duplicate of issue #58, you can work around the issue by forcing all script to be run with bash.

**Closed by ienorand** 2015-02-18 19:21 UTC

**Comment by qreeves** [comment] 2015-02-18 19:28
Should be working now, sorry.
