### ISSUE TITLE
Audio: Footstep causes crackling/popping noises

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#775] opened 2017-11-30 21:14 UTC
When playing footstep sounds (or any sound that repeats quickly, I guess), you can hear a definitive crackle with the default settings. (I attempted to increase sound channels a while back to no avail)

I tried on the following audio sinks:
 - Bluetooth audio
 - SoundBlaster X-Fi Platinum
 - Realtek 887 on-board audio chipset

I can reproduce the crackling on every one of these audio sinks.

The game also appears to be skipping some sounds.

I think the cause of the problem is SDL (2? are we even using SDL2-audio or are we still on SDL-audio/using legacy APIs?) which either doesn't cut sound properly or can't handle that many sound sources playing at once. The problem is quite aggravating when using headphones on quiet maps as the crackling and the popping is quite loud and right next to your ear.

> Archlinux x64
> Can be reproduced in both `stable` and `latest master`

I will check on Windows later this week to see if it can be reproduced on that platform as well.

**EDIT:** @zaquest can reproduce the crackling by walking diagonally, the footstep sounds crackle and pop reliably.

**Comment by qreeves** [comment] 2017-12-01 11:40
Does increasing `soundmixchans` help? I'm thinking we could maybe get away with 256 as sound cards aren't that limited anymore.

**Comment by acerspyro** [comment] 2017-12-02 16:24
I set `soundmixchans` to 1024 instead of the default 256, and it crackles the same.

If you load up the map "Castle" and go through the teleporter, the crackling is very apparent.

**Comment by qreeves** [comment] 2017-12-05 13:20
I looked into the issue and it seems the problem is with the sounds themselves. This will be fixed when we get new sounds.

**Comment by acerspyro** [comment] 2017-12-18 23:42
Here is a recording of the audio that comes out of my system. It is worse on my Linux tower, take a listen. (Output recorded from Audacity, it's exactly the same as the speaker output)

https://drive.google.com/file/d/1oNt7OUupSlTa7K2g_EzrWEqSPv_abZoo/view?usp=sharing

**Comment by zaquest** [comment] 2017-12-19 03:32
No, I can't. I have no footsteps at all when walking diagonally.

**Comment by graphitemaster** [comment] 2017-12-27 04:18
SDL2 has been having a lot of issues with sound playback ever since they went and rewrote the sound resampling code for a minor patch release for some idiotic reason. It's so bad that Tesseract simply disables sound for people on 2.0.6 see: https://websvn.tuxfamily.org/diff.php?repname=tesseract%2Fmain&path=%2Fsrc%2Fengine%2Fsound.cpp&rev=2152&peg=2152. These issues have sort of been fixed see https://bugzilla.libsdl.org/show_bug.cgi?id=3858 for more information. Tho the resampling changes still have major problems with aliasing as outlined here https://bugzilla.libsdl.org/show_bug.cgi?id=3878 this isn't a Redeclipse bug. I'm closing this.

**Closed** 2017-12-27 04:18 UTC
Labels: bug, next milestone

**Comment by acerspyro** [comment] 2018-01-04 04:28
I haven't gone mad, my sound issues disappeared when I started using the AppImage. The sound is reproducible only on ArchLinux on both my laptop and my desktop when not using the AppImage. Here are my current shared libraries used by Red Eclipse x64:

`	linux-vdso.so.1 (0x00007fffe03a3000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f399b2c8000)
	libSDL2-2.0.so.0 => /usr/lib/libSDL2-2.0.so.0 (0x00007f399afb8000)
	libSDL2_image-2.0.so.0 => /usr/lib/libSDL2_image-2.0.so.0 (0x00007f399ad90000)
	libSDL2_mixer-2.0.so.0 => /usr/lib/libSDL2_mixer-2.0.so.0 (0x00007f399ab70000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f399a958000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f399a6c8000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f399a4c0000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f399a138000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f3999de8000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f3999a30000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f3999800000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f39995f8000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f39993d8000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f39991a0000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f3998f88000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f3998cd0000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f399b608000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3998ab8000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f39988b0000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f39986a8000)
`

This is SDL 2.0.7 rather than 2.0.6. I am leaving this here for future reference.

**Comment by q009** [comment] 2019-03-22 20:53
Try it now.
