### ISSUE TITLE
Make hosting Red Eclipse servers legal for server owners

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#594] opened 2016-10-17 14:07 UTC
Ever since I played Red Eclipse, I could see all the other players' IP addresses. They were also permanently stored in demos (which anyone can download), and they are relayed to IRC channels where they're often permanently stored by people using bouncers or similar.

I believe that this behavior is illegal and thus the multiplayer guidelines (which forbid changes to the source code) force server owners to break local and global law.

Server owners in the EU are not allowed to store IP addresses of players unless they explicitly have their permission, which is not the case since the players are not asked, but happens by storing demos. Even if they were allowed to, they must not hand out the data to third parties, which happens with the demos, the scoreboard and the IRC relays.
The first issue can be resolved by turning off demos, but the latter would require a code change inserting fake addresses instead of the real ones.

The new "Privacy Shield" contract also prohibits servers located in the US to store IP addresses of clients in the EU and vice versa similarly to EU law.

To improve privacy and reduce the risk of being sued for server owners all over the world, I propose that IP addresses should only be shown to global or local moderators or higher roles, and not saved elsewhere (not even in logs).

It is understandable that these data are useful for punishing cheaters or misbehaving individuals, but this mass surveillance cannot be the solution. But it can't be that hosting a server is an illegal action, and server owners might not actually know about that.

Apart from that, every time someone is publishing a demo on the Internet (doesn't matter if it's GitHub, the RE forums or elsewhere), it is an illegal action. This would be resolved by this proposal, too.

**Comment by JeffBobbo** [comment] 2016-10-17 14:16
Sounds like this could be rememdied by simply hashing the IP.

Can you cite the relevant legislation? Perhaps this conversation is better suited for the forums too.

**Comment by qreeves** [comment] 2016-10-18 05:08
Yeah, this is a community topic, not a bug. Please move the discussion to the forums.

**Comment by acz13** [comment] 2016-11-27 02:37
What was the reason of the reopen? I thought this still needed to be moved to forums...

or maybe I missed a forum post?

**Comment by qreeves** [comment] 2016-11-27 22:42
It mostly has to do with how politically charged the topic seems to be. In the interests of keeping a friendly community, I have instead decided it is best to make an executive decision, rather than cater to a flame-war discussion on it.

**Comment by qreeves** [comment] 2017-01-23 10:20
Project completed, closing issue.

**Closed by qreeves** 2017-01-23 10:20 UTC
Labels: enhancement
