### ISSUE TITLE
Fatal signal 11 - windows

### ISSUE THREAD

**Issue by yoavst** [red-eclipse/base#323] opened 2015-07-31 19:45 UTC
Latest RE 1.5.3. crash with fatal signal 11 on entering a game.
If you can tell me how do I collect the stacktraces (Java developer, not C++), I can upload it.

**Comment by qreeves** [comment] 2015-08-01 04:10
Could you please provide information on your operating system, video card (hardware and drivers), and the contents of your `log.txt`; which can be found in your [RE home directory](http://redeclipse.net/wiki/Game_Settings#User_Content).

**Comment by yoavst** [comment] 2015-08-01 06:12
Windows 10, Intel i7 4770, HD 4600.

the log doesn't show any crash:
```
2015-07-31 22:43.10 loading enet..
2015-07-31 22:43.10 loading game..
2015-07-31 22:43.10 identity: v1.5.3-win64 client (Aurora Edition) [0xadd551f3]
2015-07-31 22:43.10 loading sdl..
2015-07-31 22:43.10 loading video..
2015-07-31 22:43.10 loading gl..
2015-07-31 22:43.10 renderer: Intel(R) HD Graphics 4600 (Intel)
2015-07-31 22:43.10 driver: 4.3.0 - Build 10.18.15.4256
2015-07-31 22:43.10 loading sound..
2015-07-31 22:43.10 allocated 32 of 32 sound channels
2015-07-31 22:43.10 loading defaults..
2015-07-31 22:43.10 loading gl effects..
2015-07-31 22:43.10 loading world..
2015-07-31 22:43.10 loading config..
2015-07-31 22:43.10 configuration loaded
2015-07-31 22:43.10 loading required data..
2015-07-31 22:43.10 loading main..
2015-07-31 22:43.14 retrieved list from master successfully
2015-07-31 22:43.26 attempting to connect to 173.28.173.201:[28801]
2015-07-31 22:43.26 connecting to 173.28.173.201:[28801]
2015-07-31 22:43.26 connected to server
2015-07-31 22:43.26 connected, starting negotiation with server
```

**Comment by shacknetisp** [comment] 2015-08-01 06:14
2 others have been getting a segfault on Windows 10, and at least one of them has an Intel HD GPU.

**Comment by qreeves** [comment] 2015-08-01 06:15
I will need to upgrade my server to Windows 10 to test it, but I have an Nvidia 9800GT in that..

**Comment by yoavst** [comment] 2015-08-01 06:41
![stacktrace](http://i.imgur.com/57CLo83.png)
Only happens if you have a saved loadout before entering to server.

**Comment by JeffBobbo** [comment] 2015-08-01 08:31
@yoavst Your stack trace lacks debugging symbols (that's why all the functions appear as "?? ()").

**Comment by yoavst** [comment] 2015-08-01 12:14
I'm running it with -g flag. I'm not C/C++ developer, so I don't know a lot about C/C++ compilers.

**Comment by yoavst** [comment] 2015-08-11 17:38
Any update? still cannot play.

**Comment by qreeves** [comment] 2015-08-12 03:01
Sorry, I did run my tests after upgrading the server and couldn't reproduce the issue. It seems to be a problem with the Intel GPU drivers. This problem has been noticed on Windows 7 and 8/8.1 machines as well, so it is not limited to Windows 10. You won't get a decent backtrace in a debugger, as the error happens inside a driver DLL.

**Comment by qreeves** [comment] 2015-09-13 05:25
Issues with Intel drivers are now fixed.

**Closed by qreeves** 2015-09-13 05:25 UTC
Labels: bug

**Comment by yoavst** [comment] 2016-04-17 17:33
Well, I've just reinstalled the game after a while. I could played this morning, but now it crashes again while i try to connect to a server.

**Comment by qreeves** [comment] 2016-04-18 04:24
Intel drivers are hit and miss, it's very hard to support them because of all the different devices and driver versions floating around. All we can suggest is trying to find a driver that does work (either by updating our rolling back). This is why most games don't officially support anything other than Nvidia/AMD. Sorry.

**Comment by yoavst** [comment] 2016-04-18 06:05
If I clean the game directory every time I open the game it works. So maybe it has something to do not only with Intel drivers?

**Comment by qreeves** [comment] 2016-04-18 06:40
If it isn't an Intel driver issue then you'll need a backtrace and a separate issue for that. If the backtrace is inside the driver DLL then it probably isn't fixable. It could just be the saved config is triggering the bug earlier during the preload phase as it tries to load a texture or something.

**Comment by qreeves** [comment] 2016-04-18 06:42
It's also worth mentioning that the rendering pipeline is very different in the development version and the bug may no longer exist (or it could be worse as it needs more from the system).

**Comment by yoavst** [comment] 2016-04-18 12:15
Now it crashes on the first time :(

Well, I guess it is a good excuse to buy a normal graphic card even though I don't really need one.

**Comment by freezurbern** [comment] 2016-04-18 13:12
> If I clean the game directory every time I open the game it works. So maybe it has something to do not only with Intel drivers?
@yoavst Do you mind explaining what exactly you're doing here? Are you deleting the configuration files?

**Comment by yoavst** [comment] 2016-04-18 13:42
@freezurbern I've deleted [RE home directory](http://redeclipse.net/wiki/Game_Settings#User_Content)

**Comment by Dziq84** [comment] 2016-04-18 18:37
I just want to note that game drops a  fatal signal 11 sometimes, and I do not use Intel CPU or graphic card. also RE its just a one game that drops this error sometimes. so its not just only a driver related issue..

**Comment by qreeves** [comment] 2016-04-19 05:29
The question is, is it happening in `master`?

**Comment by yoavst** [comment] 2016-04-19 06:11
For me yes.

**Comment by bonifarz** [comment] 2016-04-19 10:18
I have not checked this systematically, but one reproduceable segfault I get in master (not in stable) is to launch the client and start an offline race game on some maps, such as testchamber, cyanide or neodrive. Some others like hinder work fine, though. IntelHD or Nvidia GPU make no difference. No clue what the problem is here.

**Comment by qreeves** [comment] 2016-04-19 10:57
I can't reproduce it, so I'm going to need a backtrace.

**Comment by bonifarz** [comment] 2016-04-19 11:49
Sorry, I just realize it does not occur when i disable my home dir. So whatever it is, it will need a separate issue or none.
